name: Build and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  build:
    strategy:
      matrix:
        runs-on: [ ubuntu-latest ]
    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Use dune
        uses: ocaml-dune/setup-dune@52d589512797f9c73ed0bb8d2f74a50fa67b1120 # v2.0.0
